### ISSUE TITLE
Request: custom deploy action on Staging of Host level deploy cycle.

### ISSUE THREAD

**Issue by chrisLeeTW** [pinterest/teletraan#59]
First, this solution is very good. thanks for the work.

I have a idea. 

In my test, deploy action on Staging of Host level deploy cycle seems to been uncustomized. (just a untar action.)
So can we custom this deploy action, that make this deploy platform more generic?

thanks.

**Comment by sbaogang** [comment]
Thanks for the question! Did you mean to allow customization on the DOWNLOAD script? 

Currently you can just provide an empty RESTARTING script, and teletraan will untar your tar ball, and nothing more. Would that solve your case?

**Comment by chrisLeeTW** [comment]
Sorry for my poor english.

What I really want is that i want to replace the default action "teletraan will untar your tar ball"

Change to different Action, may yum install ? Something like that.

**Comment by sbaogang** [comment]
Hi chrisLeeTW,

The power of Teletraan really comes from the various deploy scripts: https://github.com/pinterest/teletraan/wiki/Integrate-with-Teletraan#make-application-deployable. You should be able to pack your deploy scripts, along with your code, into a tar file. Your deploy scripts could do the yum install, and any other things you like to do.  I am going to close this request for now ( since I believe your request is already covered), but feel free to reopen it if you think otherwise. Thanks again for your questions!
