### ISSUE TITLE
Deploy Agent python dependencies requirements

### ISSUE THREAD

**Issue by falzm** [pinterest/teletraan#64]
Hi

I'm trying to make a Debian package for the deploy agent: the python dependencies required versions are quite recent, is it really necessary? Debian provides packages for those deps, but their versions are a bit less recent: re-package all deps to the required version is quite tedious operationally...

**Comment by sbaogang** [comment]
We tend to use the latest stable version we could find. Which particular package you are referring to? I'd expect there should be no problem since we are using Python virtual environment, all dependencies should be installed through pip.

**Comment by falzm** [comment]
```python
install_requires = [
    "requests==2.9.1",
    "gevent==1.0.2",
    "lockfile==0.10.2",
    "boto>=2.39.0",
    "python-daemon==2.0.6"
]
```

Our industrialisation process doesn't imply installing Python packages using `pip` on production servers, only Debian packges – which can be built from pip, but in this case dependencies are too recent.

**Comment by sbaogang** [comment]
I would suggest, when you build deploy-agent into Debian package, you could override the setup.py and use the versions you like. I would expect lower version should work as well. But do let us know if otherwise. I am closing this right now, feel free to reopen or create new request for further questions
