### ISSUE TITLE
Why you choose pull architecture? 

### ISSUE THREAD

**Issue by a93ushakov** [pinterest/teletraan#69]
Why `teletraan` use `puppet`-style pull-architecture?
Why not like `ansible` push-design - without agents on clients side - why not enough `ssh`?

**Comment by sbaogang** [comment]
Thanks for your question, the following is what I had for one of the Teletraan talks:
=============
... I would recommend to use the Pull model in this case, it will greatly simplify your design and implementation. when you have tens of thousands of hosts need to be updated all the time, chances are some of the hosts will temporarily off-line due to network partition, or just failed to update due to some transient errors. to keep track of all these different cases, failures, retries, timeouts, is very hard. A pull based system will make the design much simpler...
